<?php

namespace tq\plcr\listingsBundle\Entity;

/**
 * SlotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlotRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllSortByName() {
    $query = $this->createQueryBuilder('s')
      ->orderBy('s.simbolo')
      ->getQuery();
    $res = $query->getResult();
    return $res;
  }
}
